# Generated by Jan on 2024-02-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_access_requested_date'),
        # this is associated with the wrong base migration
        # and should cause an exception
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
    ]
